bookings/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import LoginView  # Import Django's built-in login view

# URL pattern order should go from the least to the most specific to ensure that only one path matches.

urlpatterns = [

    # This is what is shown on the Homepage test
    path("", views.HomePageView.as_view(), name="home"),

    # Page where User can create a new booking
    # path("create-booking/", views.BookingCreateView.as_view(), name="create_booking"),
    path("create-booking/", views.booking_form, name="create_booking"),

    # User dashboard page where they can see all their bookings
    path("dashboard/", views.BookingListView.as_view(), name="user_dashboard"),

    # So User can update an existing booking
    path("update-booking/<int:pk>/", views.BookingUpdateView.as_view(), name="update_booking"),

    # So User can delete an existing booking
    path("delete-booking/<int:pk>/", views.BookingDeleteView.as_view(), name="delete_booking"),

    # Admin Dashboard - list of all the users bookings for the Admin only
    path("admin-dashboard/", views.AdminBookingListView.as_view(), name="admin_dashboard"),
]

late_night_cafe/urls.py
from django.contrib import admin
from django.urls import path, include

# URL pattern order should go from the least to the most specific to ensure that only one path matches.
urlpatterns = [
    path("", include("bookings.urls"), name="bookings-urls"), # This include all app-specific URLs
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
]

bookings/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone # Pulls in default timezone info which is Europe/London

# Create your models here.

# Model for making a booking for an available table
class Booking(models.Model):
    
    TABLE_CHOICES = [
        ("1", "Table 1"),
        ("2", "Table 2"),
        ("3", "Table 3"),
    ]

    TIMESLOT_CHOICES = [
        ("18:00", "6 PM"),
        ("19:00", "7 PM"),
        ("20:00", "8 PM"),
        ("21:00", "9 PM"),
        ("22:00", "10 PM"),
        ("23:00", "11 PM"),
        ("00:00", "12 AM"),
        ("01:00", "1 AM"),
        ("02:00", "2 AM"),
        ("03:00", "3 AM"),
        ("04:00", "4 AM"),
        ("05:00", "5 AM"),
    ]

    NUM_GUESTS_CHOICES = [(i, i) for i in range(1, 5)] # Limits number of guests from min 1 to max 4. Futureproofing in case more tables are added with varying seat numbers.

    booking_id = models.AutoField(primary_key = True) # Unique booking id
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bookings') # Relationship to User model. If user is deleted, booking will be deleted too.
    table_booked = models.CharField(choices=TABLE_CHOICES, default="1") # Lists choice of tables in cafe.
    booking_date = models.DateField(null = False, blank = False) # Date when customer wants to book table - Mon-Sun. Date & time separate to allow for more flexibility for users to modify their booking. Field needs a value input. 
    booking_time = models.CharField(max_length = 6, choices=TIMESLOT_CHOICES, default="6 PM") # Lists bookable timeslots (1 hour slots from 6pm-6am).
    num_of_guests = models.IntegerField(choices=NUM_GUESTS_CHOICES, default=1) # Default number of guests is set to 1. Field needs a value input. 
    special_requests = models.TextField(null = True, blank = True) # Textfield so customers can add allergy info, birthday treats, etc. Optional field.
    booking_created_at = models.DateTimeField(auto_now_add = True) # Sets timestamp only when the record is created
    booking_updated_at = models.DateTimeField(auto_now = True) # Updates timestamp every time the record is saved

    class Meta:
        verbose_name = "Booking"
        verbose_name_plural = "Bookings"
        ordering = ["booking_date", "booking_time", "table_booked"] # Shows bookings in chronological order (by date, then time, then table number)
        unique_together = ["booking_date", "booking_time", "table_booked"] # Ensures that the same table can't be booked on the same date/time

    def __str__(self):
        return f"Booking for {self.user} ({self.booking_id}) at {self.table_booked} on {self.booking_date} at {self.booking_time} for {self.num_of_guests}." # Method returns a string summarising a table booking

bookings/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm  # Import Django's built-in UserCreationForm
from django.contrib.auth.models import User  # Import Django's built-in User model
from django.core.exceptions import ValidationError  # Import used to raise validation errors in forms
from .models import Booking  # Import local Booking model
import datetime  # For handling date and time operations

# Form users fill in to register and sign up to the site
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "username", "password1", "password2"]

# Form users fill in to create a booking
class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ["booking_date", "booking_time", "table_booked", "num_of_guests", "special_requests"]

    # Form validation: if a user tries to pick an invalid booking date, they'll get immediate feedback
    def clean_booking_date(self):
        booking_date = self.cleaned_data.get("booking_date")
        today = datetime.date.today()
        one_year_from_now = today + datetime.timedelta(days=365)

        # Check if the booking date is in the past
        if booking_date < today:
            raise ValidationError("The booking date cannot be in the past. Please select another date.")
        
        # Check if the booking date is more than one year in advance
        if booking_date > one_year_from_now:
            raise ValidationError("Sorry, we don't accept bookings more than one year in advance. Please select another date.")
        
        return booking_date

bookings/views.py
from django.shortcuts import render, get_object_or_404, reverse # function is a shortcut for rendering a template and returning an HTTP response
from django.views import generic # Import Django's built-in generic views
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.views import LoginView  # Import Django's built-in login view
from django.contrib.auth.forms import UserCreationForm  # Import UserCreationForm for sign up
from django.urls import reverse_lazy # Handles URL redirection
from .models import Booking # Import local Booking model
from .forms import CustomUserCreationForm, BookingForm # Import local CustomUserCreationForm and Booking Form
from .mixins import UserIsOwnerMixin, SuperuserRequiredMixin # Import mixins.py
from django.shortcuts import redirect


# Note: for Login View = using Django's built-in LoginView

# GENERAL VIEWS
# Latte Night Cafe Homepage
class HomePageView(generic.TemplateView):
    template_name = "bookings/index.html"


# ADMIN VIEWS

# Admin Dashboard - lists bookings for all users for the logged-in site admin

class AdminBookingListView(SuperuserRequiredMixin, generic.ListView): # Admin = Superuser for now, can expand permissions to staff Admin when business expands
    model = Booking
    template_name = "bookings/admin_dashboard.html"
    context_object_name = "bookings"
    success_url = reverse_lazy("admin_dashboard")

    def get_queryset(self): 
        queryset = Booking.objects.all() # Filters bookings so Admin can see all bookings

        # Ability to sort bookings
        sort_by = self.request.GET.get('sort_by', 'booking_date')  # Default sort by booking date
        sort_order = self.request.GET.get('sort_order', 'asc')     # Default sort order is ascending

        if sort_order == 'desc': # If sort order is descending
            sort_by = f'-{sort_by}'

        queryset = queryset.order_by(sort_by)

        return queryset


def booking_form(request, booking_id=None):
    if not request.user.is_authenticated:
        messages.add_message(request, messages.ERROR, "You need to be logged in to create a booking.")
        return redirect(reverse("account_login"))

    if booking_id: # Checks to see if booking_id is provided
        booking = get_object_or_404(Booking, id=booking_id) # If there is a booking id, then the form will populate with data from that existing booking
    else:
        booking = None # If there is no booking id, then the form will be blank and new

    # This block handles the form submission
    if request.method == "POST":
        form = BookingForm(request.POST, instance=booking)
        
        if form.is_valid(): # Checks if form's validation rules are met
            booking = form.save(commit=False)  # Doesn't commit form to the database yet
            booking.user = request.user  # Assigns the logged-in user to the booking
            booking.save()  # Now saves form to the database
            messages.add_message(request, messages.SUCCESS, "Booking successfully created.")
            return redirect("admin_dashboard") # Redirects back to Admin Dashboard
   
   # This block handles the GET requests and displays the form
    else:
        form = BookingForm(instance=booking) # Empty form for user to fill in
 
    # This block renders the form template
    return render(
        request,
        "bookings/booking_form.html",
        {"form": form, "booking": booking}
    )



# USER VIEWS
# User Dashboard - lists bookings for the logged in user
class BookingListView(generic.ListView):
    model = Booking
    template_name = "bookings/user_dashboard.html"
    context_object_name = "bookings"

    def get_queryset(self): # Ability to sort bookings

        queryset = Booking.objects.filter(user=self.request.user) # Filters bookings so current user can only see their own
        sort_by = self.request.GET.get('sort_by', 'booking_date')  # Default sort by booking date 
        sort_order = self.request.GET.get('sort_order', 'asc')     # Default sort order is ascending 

        if sort_order == 'desc': # If sort order is descending
            sort_by = f'-{sort_by}'

        queryset = queryset.order_by(sort_by)

        return queryset


# Create a Booking Form
class BookingCreateView(generic.CreateView):
    model = Booking
    form_class = BookingForm
    template_name = "bookings/booking_form.html"
    success_url = reverse_lazy("user_dashboard") # Will redirect to user dashboard

def booking_form(request, booking_id=None):
    if not request.user.is_authenticated:
        messages.add_message( # Feedback for user letting them know they have to sign in to make a booking
                request, messages.ERROR,
                "You need to be logged in to create a booking."
        )
        return redirect(reverse("account_login")) # Redirects a non-logged in User to sign in page so they can log in/sign up so they can make a booking

    if booking_id: # Checks to see if booking_id is provided
        booking = get_object_or_404(Booking, id=booking_id) # If there is a booking id, then the form will populate with data from that existing booking
    else:
        booking = None # If there is no booking id, then the form will be blank and new
    

    # This block handles the form submission
    if request.method == "POST":
        print("Received a POST request") # Prints message to console for debugging purposes
        form = BookingForm(request.POST, instance=booking) # Creates an instance of the form with the submitted data
        
        if form.is_valid(): # Checks if form's validation rules are met
            booking = form.save(commit=False)  # Doesn't commit form to the database yet
            booking.user = request.user  # Assigns the logged-in user to the booking
            booking.save()  # Now saves form to the database
            messages.add_message( # Feedback for user confirming their booking
                request, messages.SUCCESS,
                "Booking submitted. We look forward to your visit!"
            )
            return redirect("user_dashboard") # User is returned to dashboard where they can see their booking/s

    # This block handles the GET requests and displays the form
    else:
        form = BookingForm(instance=booking) # Empty form for user to fill in

    # This block renders the form template
    return render(
        request,
        "bookings/booking_form.html",
        {"form": form, "booking": booking},
    )

# Update/Edit a Booking
class BookingUpdateView(UserIsOwnerMixin, generic.UpdateView):
    model = Booking
    form_class = BookingForm
    template_name = "bookings/update_booking.html"

    def get_success_url(self): # if it's the admin/superuser making the booking amend they will be redirected back to the Admin Dashboard
        if self.request.user.is_superuser:
            return reverse_lazy("admin_dashboard")
        return reverse_lazy("user_dashboard")

    def form_valid(self, form):
        try:
            response = super().form_valid(form) # Saves the form/updated data to the database
            messages.success(self.request, "Your booking has been updated!")  # Sends success feedback to user
            return response
        except Exception as e: # If an error occurs during form processing then this block of code will trigger
            messages.error(self.request, "Oops! There was a problem updating your booking. Please try again.")  # Sends error feedback to user
            return self.form_invalid(form)

    def form_invalid(self, form): # Handles the error
        # This will re-render the form with error messages so the user can correct their booking details
        messages.error(self.request, "Whoops! There was an issue updating your booking. Please check your booking details and try again.")
        return super().form_invalid(form)

# Delete a Booking
class BookingDeleteView(UserIsOwnerMixin, generic.DeleteView):
    model = Booking
    template_name = "bookings/confirm_delete.html"
    success_url = reverse_lazy("user_dashboard") # Will redirect to user dashboard

    def get_success_url(self): # if it's the admin/superuser making the booking amend they will be redirected back to the Admin Dashboard
        if self.request.user.is_superuser:
            return reverse_lazy("admin_dashboard")
        return reverse_lazy("user_dashboard")

    def delete(self, request, *args, **kwargs): #This calls the parent class's delete method, which handles the deletion of the object.
        response = super().delete(request, *args, **kwargs)
        messages.success(self.request, "Your booking has been deleted!")  # Feedback for user that confirms their booking has been delete
        return response

bookings/templates/bookings/admin_booking_list.html
{% extends "base.html" %}

{% block content %}

<!-- admin_booking.html content starts here -->
<div class="container-fluid">
    <div class="row">

        <!-- Booking Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for booking in booking_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                <div class="image-flash">
                                    <p class="author">User: {{ booking.user }}</p>
                                </div>
                            </div>
                            <a href="#" class="post-link">
                                <h2 class="card-title">Booking ID: {{ booking.booking_id }}</h2>
                            </a>

                            <hr />
                            <p class="card-text text-muted h6">
                                Date: {{ booking.booking_date }}<br>
                                Time: {{ booking.booking_time }}<br>
                                Table: {{ booking.table_booked }}<br>
                                Guests: {{ booking.num_of_guests }}
                            </p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
   
</div>

<!-- Admin Booking List.html content ends here -->
{% endblock %}

bookings/templates/bookings/admin_dashboard.html
{% extends "base.html" %}

{% block content %}

<!-- Admin Dashboard content starts here -->


<!-- Displays all user's bookings in an easy to read table -->
<div class="container mt-4">
    <h1 class="text-center">All Bookings for Latte Night Cafe</h1>

    <!-- Allows Admin to sort through all bookings -->

    <!-- Sorting Form -->
    <form method="get" class="mb-4">
        <div class="row">
            <h2> Sort by: </h2>
            <div class="col">
                <select name="sort_by" class="form-control">
                    <option value="booking_date" {% if request.GET.sort_by == 'booking_date' %}selected{% endif %}>Date
                    </option>
                    <option value="user" {% if request.GET.sort_by == 'user' %}selected{% endif %}>User</option>
                    <option value="special_requests"
                        {% if request.GET.sort_by == 'special_requests' %}selected{% endif %}>Special Requests</option>
                    <!-- Add more here sorting options as needed -->
                </select>
            </div>

            <div class="col">
                <select name="sort_order" class="form-control">
                    <option value="asc" {% if request.GET.sort_order == 'asc' %}selected{% endif %}>Ascending</option>
                    <option value="desc" {% if request.GET.sort_order == 'desc' %}selected{% endif %}>Descending
                    </option>
                </select>
            </div>

            <div class="col">
                <button type="submit" class="btn btn-primary">Sort</button>
            </div>

        </div>
    </form>


    {% if bookings %}
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Booking ID</th>
                <th>User</th>
                <th>Date</th>
                <th>Time</th>
                <th>Table</th>
                <th>Guests</th>
                <th>Special Requests</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for booking in bookings %}
            <tr>
                <td>{{ booking.booking_id }}</td>
                <td>{{ booking.user.username }}</td>
                <td>{{ booking.booking_date }}</td>
                <td>{{ booking.booking_time }}</td>
                <td>{{ booking.table_booked }}</td>
                <td>{{ booking.num_of_guests }}</td>
                <td>{{ booking.special_requests }}</td>
                <td>
                    <!-- Buttons that give the Admin the option to edit or delete all booking -->
                    <a href="{% url 'update_booking' booking.pk %}" class="btn btn-primary btn-sm">Edit Booking</a>
                    <a href="{% url 'delete_booking' booking.pk %}" class="btn btn-danger btn-sm">Delete Booking</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- If there are no bookings, this message will display instead -->
    {% else %}
    <p class="text-center">No bookings found.</p>
    {% endif %}

    <!--Create Booking Button -->
    <div class="text-center">
        <a href="{% url 'create_booking' %}" class="btn btn-warning btn-lg">Create a Booking</a>
    </div>
</div>
{% endblock %}






















<!-- OLD CODE - delete when new code finished
admin_booking.html /admin_booking_list content starts here

Admin Dashboard content starts here

<div class="container-fluid">
    <div class="row">

        <!-- Booking Entries Column --
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for booking in booking_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                <div class="image-flash">
                                    <p class="author">User: {{ booking.user }}</p>
                                </div>
                            </div>
                            <a href="#" class="post-link">
                                <h2 class="card-title">Booking ID: {{ booking.booking_id }}</h2>
                            </a>

                            <hr />
                            <p class="card-text text-muted h6">
                                Date: {{ booking.booking_date }}<br>
                                Time: {{ booking.booking_time }}<br>
                                Table: {{ booking.table_booked }}<br>
                                Guests: {{ booking.num_of_guests }}
                            </p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
   
</div>




 OLD CODE - delete when new code finished -->

bookings/templates/bookings/booking_form.html
<!-- Create Booking Form Template-->

{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}


<h2>Create a Booking</h2>

<p> To create a booking, please <a class="link" href="{{ login_url }}">log in</a>. <br>
    If you have not created an account yet, then please <a class="link" href="{{ signup_url }}">sign up</a> first.</p>
<p>Please select a date (YYYY-MM-DD), time and table you would like to book at Latte Night Cafe. Fields with an * are
    required.</p>
<p>If the table at your desired date and time is booked, please try another table. <br> If these tables are also already
    booked, please try a different time or date.</p>

    <form method="post">
    <!-- This token protects app from Cross-Site Request Forgery (CSRF) attacks, ensures submission comes from authenticated user -->
    {% csrf_token %}
    <!-- Makes form using Crispy Forms -->
    {{ form|crispy }}

    <button class="btn btn-warning btn-lg" type="submit">Create a Booking</button>

</form>


{% endblock %}

bookings/templates/bookings/confirm_delete.html
<!-- Delete a Booking Template-->

{% extends "base.html" %}

{% block content %}

<h2>Confirm Booking Cancellation</h2>

<p>Are you sure you want to delete your booking at Latte Night Cafe for {{ object.table_booked }} on
    {{ object.booking_date }} at {{ object.booking_time }}?</p>

<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-sm">Yes, delete my booking</button>
    <a href="{% url 'user_dashboard' %}" class="btn btn-warning btn-sm">No, keep my booking</a>
</form>

{% endblock %}

bookings/templates/bookings/create_booking.html
<!-- Create Booking Form Template-->

{% extends "base.html" %}

{% block content %}
<h2>Create a Booking</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Booking</button>
</form>
{% endblock %}

bookings/templates/bookings/delete_booking.html
<!-- Delete a Booking Template-->

{% extends "base.html" %}

{% block content %}
<h2>Confirm Delete</h2>
<p>Are you sure you want to delete the booking for {{ object.table_booked }} on {{ object.booking_date }} at {{ object.booking_time }}?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete my booking</button>
    <a href="{% url 'user_dashboard' %}">No, please keep my booking</a>
</form>
{% endblock %}

bookings/templates/bookings/index.html
{% extends "base.html" %}

{% block content %}

<!-- Hero Section starts -->
<div class="hero-section">
    <div class="container-fluid">
        <div class="row">
            <!-- Hero Image -->
            <div class="col-12">
                <div class="hero-image"
                    style="background-image: url('https://res.cloudinary.com/dl5c9ood9/image/upload/v1723576168/cup-coffee-table-front-street-with-city-lights-background_pfpyui.jpg'); height: 400px; background-size: cover; background-position: center;"
                    aria-label="Hero image showing a steaming cup of coffee in the foreground and a city street at night in the background">
                    <div class="hero-overlay text-center" style="padding: 100px 0;">
                        <h1 class="display-4 text-white text-overlay"><b>Welcome to Latte Night Cafe</b></h1> <br>
                        <p class="lead text-white text-overlay"><b><em>where late nights become latte nights</em></b>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="text-center">
    <a href="{% url 'create_booking' %}" class="btn btn-warning btn-lg">Create a Booking</a>
</div>

<!-- Hero Section starts ends -->
{% endblock %}

bookings/templates/bookings/post_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Views Part 1</title>
</head>

<body>
    <h1>Posts list</h1>
    {% for post in object_list %}
    <h2>{{post.title}}</h2>
    <p>{{post.excerpt}}</p>
    <p>Author: {{post.author}}</p>
    {% endfor %}
</body>

</html>

bookings/templates/bookings/update_booking.html
<!-- Update Booking Template -->

{% extends "base.html" %}

{% block content %}

<h2>Update Booking</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-warning btn-sm">Update Booking</button>
    <a href="{% url 'delete_booking' booking.pk %}" class="btn btn-danger btn-sm">Delete Booking</a>
    <a href="{% url 'user_dashboard' %}" class="btn btn-secondary btn-sm">Cancel</a>
</form>

{% endblock %}

bookings/templates/bookings/user_dashboard.html
<!-- User Dashboard Template-->
{% extends "base.html" %}

{% block content %}

<!-- Allows User to sort through their bookings -->

<!-- Sorting Form -->
<form method="get" class="mb-4">
    <div class="row">
        <h2> Sort by: </h2>
        <div class="col">
            <select name="sort_by" class="form-control">
                <option value="booking_date" {% if request.GET.sort_by == 'booking_date' %}selected{% endif %}>Date
                </option>
                <!-- Add more here sorting options as needed -->
            </select>
        </div>

        <div class="col">
            <select name="sort_order" class="form-control">
                <option value="asc" {% if request.GET.sort_order == 'asc' %}selected{% endif %}>Ascending</option>
                <option value="desc" {% if request.GET.sort_order == 'desc' %}selected{% endif %}>Descending</option>
            </select>
        </div>

        <div class="col">
            <button type="submit" class="btn btn-primary">Sort</button>
        </div>

    </div>
</form>


<!-- Displays user's bookings in an easy to read table-->
<div class="container mt-4">
    <h1 class="text-center">Your Bookings</h1>
    {% if bookings %}
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Booking ID</th>
                <th>Date</th>
                <th>Time</th>
                <th>Table</th>
                <th>Guests</th>
                <th>Special Requests</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for booking in bookings %}
            <tr>
                <td>{{ booking.booking_id }}</td>
                <td>{{ booking.booking_date }}</td>
                <td>{{ booking.booking_time }}</td>
                <td>{{ booking.table_booked }}</td>
                <td>{{ booking.num_of_guests }}</td>
                <td>{{ booking.special_requests }}</td>
                <td>
                    <!-- Buttons that give the user the option to edit or delete their booking -->
                    <a href="{% url 'update_booking' booking.pk %}" class="btn btn-primary btn-sm">Edit Booking</a>
                    <a href="{% url 'delete_booking' booking.pk %}" class="btn btn-danger btn-sm">Delete Booking</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <!-- If there are no bookings, this message will display instead -->
    {% else %}
    <p class="text-center">No bookings found.</p>
    {% endif %}

    <!--Create Booking Button -->
    <div class="text-center">
        <a href="{% url 'create_booking' %}" class="btn btn-warning btn-lg">Create a Booking</a>
    </div>
</div>
{% endblock %}